name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: webapp/package-lock.json
      - name: Install
        run: |
          npm cache clean --force
          npm install
      - name: Test
        run: npm run test:coverage
      - name: report coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: ./webapp
          path-to-lcov: ./webapp/coverage/lcov.info
